export const GITHUB_CLIENT_ID = import.meta.env.VITE_GITHUB_CLIENT_ID;
export const API_BASE_URL = 'https://authy-app-backend.onrender.com';
// export const API_BASE_URL = 'http://localhost:5000';
export const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID;
export const FACEBOOK_CLIENT_ID = import.meta.env.VITE_FACEBOOK_CLIENT_ID;
export const REDIRECT_URI = 'https://lucent-mermaid-ff4214.netlify.app/';
// export const REDIRECT_URI = 'http://localhost:5173';
export const TWITTER_CLIENT_ID = import.meta.env.VITE_TWITTER_CLIENT_ID;
export const REDIRECT_URL_NGROK = 'https://lucent-mermaid-ff4214.netlify.app/';